name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./...

      - name: Build (amd64)
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o job-darwin-amd64 .

      - name: Build (arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o job-darwin-arm64 .
